### ISSUE TITLE
Windows exe's do not open

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersWeb#11]
In fact, the JRE does not appear to be included in any of these  apps (did you click the button on export?), so its probably a fluke that it runs on my mac as well...

![capturedaniel](https://cloud.githubusercontent.com/assets/737638/20555954/b3da702c-b19f-11e6-99d9-5c255230987c.PNG)

**Comment by dhowe** [comment]
Need to repackage with one of [these methods](https://robbamforth.wordpress.com/2016/01/29/java-how-to-bundle-a-java-app-as-an-windows-executable-exe-jar-to-exe-6/)...

**Comment by dhowe** [comment]
For now lets post the following:
1) The Windows builds as is, but with a Note on the page that Java 1.8x is required on the machine
2) The NEW mac app (~150mb) , with only the .app and .rtf files in the zip
3) The linux is fine as is

Note that these are all in the applications folder of the 'Readers2016_asPosted' branch of [this](https://github.com/dhowe/RELC3) repo

**Comment by cqx931** [comment]
Please check
https://github.com/dhowe/ReadersWeb/pull/12

**Comment by dhowe** [comment]
We need to included a JRE along with the windows app. @cqx931 can you try with install4j as described here: https://robbamforth.wordpress.com/2016/01/29/java-how-to-bundle-a-java-app-as-an-windows-executable-exe-jar-to-exe-6/
