### ISSUE TITLE
Header image disappears on scroll

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersWeb#20]
![image](https://user-images.githubusercontent.com/737638/28465276-b9489908-6e5a-11e7-8f42-86c3c9f8de2b.png)

**Comment by cqx931** [comment]
What's the exact steps to reproduce it?
On my computer, it takes 1-2 seconds for the header image to load, but the header image is always there.

**Comment by dhowe** [comment]
I got the above behavior on chromium simply by scrolling down and then scrolling back up to the top (the image would be there at the start, then disappear after scrolling up again)

**Comment by cqx931** [comment]
I tried it both on my computer and on even on my friend's computer, but I still can't reproduce this.

**Comment by dhowe** [comment]
ok, closing for now as I can no longer reproduce
