### ISSUE TITLE
Information missing for 'Common Tongues' installation

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersWeb#21]
As for other 'installation' items, the darker, semi-transparent overlay at http://thereadersproject.org/installations/ct.html#ct should have details of the Edinburgh 2012 installation:

Installed for the juried exhibition associated with the ELMCIP conference and festival, 'Remediating the Social,' in the Inspace Gallery, University of Edinburgh, Nov 1-17, 2012.

**Comment by cqx931** [comment]
Thanks! The information has been added accordingly.
https://github.com/dhowe/ReadersWeb/pull/22

**Comment by shadoof** [comment]
Verified
