### ISSUE TITLE
Add recent ELO award

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersWeb#24]

**Comment by shadoof** [comment]
@dhowe I'm happy to do this but would like to do so in concert with other changes:
- change "writings" to either "scholarship" or "research" or "recognition" - your choice - and move the current "about the readers project" -> "Citing the Readers" to this (to-be-re-organized) section of the site
- "Citing the Readers" is wrong from my PoV anyway, if the goal is/was to provide a standard way, bibliographically, to cite the project as such (which I'm sure scholar/researchers will appreciate
- add an "Awards/Grants" sub-section to "scholarship"/"research"/"recognition" (allowing for some redundancy with "featured outcomes"

**Comment by shadoof** [comment]
also:
- Move PUBLICATIONS BY ARTISTS to top of page

**Comment by shadoof** [comment]
Added the ELO award, after 'Installations' to 'Featured Outcomes' with a pull request. Closing this and open separate issue assigned to dhowe in case you want to do anything about the stuff in these comments.
