### ISSUE TITLE
Verify that 'Downloadables' actually run

### ISSUE THREAD

**Issue by dhowe** [dhowe/ReadersWeb#25]
http://thereadersproject.org/download.html#download1

they don't for me... I see the image below

if not, we should remove them

![screen shot 2018-07-12 at 3 49 52 pm](https://user-images.githubusercontent.com/737638/42620575-e8e4d16c-85ed-11e8-9f2c-21312e8e09b4.png)

**Comment by shadoof** [comment]
@dhowe fixed with a6166a6. I pushed a commit with the fixed jar and tested the others. If you're satisfied with this, please make the jar live (however you do this) and then close.

**Comment by shadoof** [comment]
they do run
