### ISSUE TITLE
more for writing about the Readers

### ISSUE THREAD

**Issue by shadoof** [dhowe/ReadersWeb#26]
Andersen, Christian Ulrik, and Søren Bro Pold. The Metainterface: The Art of Platforms, Cities, and Clouds.  Cambridge: MIT Press, 2018.
Discusses The Readers Project, pp. 61-64; How it is in Common Tongues pp. 64-69

**Comment by dhowe** [comment]
'Aesthetic Animism, Digital Poetry's Ontological Implications' by David Jhave Johnston, 2016
'Electronic Literature' by Scott Rettberg , 2018

'Poetics in Action. Time and Code in the Poetry of John Cayley and the Poets of Rozdzielczość Chleba' by Mariusz Pisarski: http://fp.amu.edu.pl/please-translate-in-en_us-poetyka-w-dzialaniu-czas-i-kod-w-poezji-johna-cayleya-i-poetow-rozdzielczosci-chleba/

"As a practitioner (a publisher and producer) of electronic literature, I have not encountered a more complex and radical work in recent years than the series of poetic programs prepared by John Cayley and Daniel C. Howe that constitute the cycle The Readers Project (2010–2016). Individual instalments of this long-term project contain the whole gamut of complexity that code in its proper function brings to poetry and poetics: the programmable function of transforming a poem’s content, style, rhetoric, and context."


'Rethinking Comparative Literature: Literary Studies in the Age of Electronic Media', by Jörgen Schäfer  http://www.ieeff.org/f18schafer.pdf

**Comment by shadoof** [comment]
all the above is online, closing
