### ISSUE TITLE
Broken link in writings.html

### ISSUE THREAD

**Issue by cqx931** [dhowe/ReadersWeb#3]
Can't find this pdf with google.

The spread representing the Common Tongues installation.
![image](https://cloud.githubusercontent.com/assets/3056154/18467945/634edc72-79d4-11e6-889b-5759e94d9db4.png)

**Comment by dhowe** [comment]
http://rednoise.org/readers/images/cayleyhowecatspreadv4.pdf

**Comment by cqx931** [comment]
fixed
